# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
#

options:
  tsdb_block_retention_period:
    default: 2h
    description: |
      Length of time for which metrics TSDB blocks are
      stored locally before being shipped to long term
      storage.
    type: string
